### ISSUE TITLE
Media import issues

### ISSUE THREAD

**Issue by BlackV** [OSDeploy/OSDBuilder#11]
Importing media (VLSC Media)

Source Path:    D:\
-Image File:    D:\Sources\install.wim
-Image Index:   1
-Name:          Windows Server 2019 Standard
-Architecture:  x64
-Edition:       ServerStandard
-Type:          Server Core
-Languages:     en-US
-Build:         17763
-Version:       10.0.17763.107
-SPBuild:       107
-SPLevel:       0
-Bootable:      No
-WimBoot:       False
-Created Time:  10/30/2018 10:43:41
-Modified Time: 10/30/2018 11:13:56
**-UBR:           17763.**
-OSMGuid:       d334e407-ab40-48ea-8218-35c971657a5f

Imports the media OK
BUT note the UBR is set to 17763. not 17763.0, 17763.1, etc

So when you attempt to update the media with  `update-osmedia -Download -Execute` or `update-osmedia -ShowAllOSMedia`
your custom properties does this `UBR = [version]$OSMUBR` (line 343 in Get-OSMedia) and dies a horrible death

I feel like I've done something wrong as ALL the media I've imported (from mounted ISO, win10 1903,win2016, win 2019)

this is a fresh install of OSDBuilder using

`Find-Module osdbuilder | Install-Module -Scope CurrentUser -Force`
`Import-Module OSDBuilder`
`Get-OSDBuilder -SetPath E:\osdbuilder -Verbose`

**Comment by OSDeploy** [comment]
The UBR shows -UBR: 17763.  This means that the media did not import properly.  Delete the problem OSMedia and the issue will go away

**Comment by BlackV** [comment]
I have done that, same issue.
But I'm guessing its something at my end, I'll close this
