### ISSUE TITLE
Null path in Initialize-OSDBuilder.ps1 19.11.12.0

### ISSUE THREAD

**Issue by UbZUN91qoLBmzn7EFKSX** [OSDeploy/OSDBuilder#17]
C:\Program Files\WindowsPowerShell\Modules\OSDBuilder\19.11.12.0\Public\Initialize-OSDBuilder.ps1: 41 Carácter: 45
JsonLocal               = Join-Path $global:GetOSDBuilderHome 'OSDBui
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand

**Comment by OSDeploy** [comment]
Can you test on version 19.11.12.1?  Also, have you closed your PowerShell session and opened a new one after updating?

**Comment by pschoepp** [comment]
I'm also getting an error: 

Join-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At C:\Program Files\WindowsPowerShell\Modules\OSDBuilder\19.11.12.1\Public\Initialize-OSDBuilder.ps1:41 char:45

**Comment by andrewtchilds** [comment]
Getting the same thing on a fresh install of 19.11.12.1

https://i.imgur.com/pqiSWY5.png

**Comment by andrewtchilds** [comment]
Submitted pull request https://github.com/OSDeploy/OSDBuilder/pull/18 to fix.

**Comment by UbZUN91qoLBmzn7EFKSX** [comment]
The issue 

> 
> 
> Can you test on version 19.11.12.1? Also, have you closed your PowerShell session and opened a new one after updating?

The issue persist on version 19.11.12.1

Join-Path : No se puede enlazar el argumento al parámetro 'Path' porque es nulo.
En C:\Program Files\WindowsPowerShell\Modules\OSDBuilder\19.11.12.1\Public\New-OSDBuilderContentPack.ps1: 112
Carácter: 40
+ ...     if (!(Test-Path (Join-Path $SetOSDBuilderPathContentPacks "$Name\ ...
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCom
   mand

**Comment by OSDeploy** [comment]
Test today's release for the fix

**Comment by UbZUN91qoLBmzn7EFKSX** [comment]
It seems the fix is working correctly.
