### ISSUE TITLE
KB4489894 missing in catalog file

### ISSUE THREAD

**Issue by svenvanrijen** [OSDeploy/OSDBuilder#2]
Hi @OSDeploy,

can you please edit https://github.com/OSDeploy/OSDBuilder/blob/master/Catalogs/Windows%2010.xml and add CU KB4489894 (http://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=3479e30e-0cdb-47e6-9eb5-3b3efbe508df). This CU will replace KB4489868 which is currently still in the XML.

Thank you in advance!

Kind regards,
Sven

**Comment by StevenNoel** [comment]
Looks like 2019-03 KB4489889 CU for 2016 as well.

**Comment by OSDeploy** [comment]
Nope.
Please read the following post concerning the types of Updates [https://www.osdeploy.com/blog/microsoft-update-releases](url)

I have confirmed that these Updates are not in WSUS, but they are in Microsoft Update Catalog (website).  OSDBuilder uses WSUS Updates which are B Releases or On Demand.  The URL I linked explains more but I suggest you validate your builds against WSUS

![image](https://user-images.githubusercontent.com/12970006/55532011-ef718c00-5671-11e9-82c1-1c739a84a86a.png)

**Comment by OSDeploy** [comment]
FYI:  If you absolutely MUST have these Updates applied in your OS, you can add them to an OSBuild as a Package or write a PowerShell Script.  Either of these can be added to an OSBuild Task to apply the Cumulative Update.
Thanks!
David Segura
