### ISSUE TITLE
Windows apply KB4524570 again. 

### ISSUE THREAD

**Issue by felipee07** [OSDeploy/OSDBuilder#20]
Hi,  

I'm having problems applying LCU,  after import my vlsc iso with -Update -BuildNetFX,  Windows will download and install the KB4524570 again. 

ISO: Windows 10 x64 1909 from VLSC.

**Comment by felipee07** [comment]
I’ve managed to sort the this out, reading previous Issues. If you install NetFX, Windows have to install LCU again, for whatever reason.

**Comment by OSDeploy** [comment]
Sorry for not leaving this comment prior, but yes, if you install NetFX, the LCU is ALWAYS reinstalled.
