### ISSUE TITLE
Question: Include Optional Updates

### ISSUE THREAD

**Issue by joey-grant** [OSDeploy/OSDBuilder#29]
When running Update-OSMedia, is there currently a way to include all available optional Windows updates without the need to specify them by name?

**Comment by Misha305** [comment]
What syntax are you using to specify them by name i.e post your powershell cmd.

**Comment by munkey01** [comment]
This is what I use currently. It does great, except for the optional updates.
```
Mount-DiskImage -ImagePath $ISOPath
Import-OSMedia -ImageIndex 3 -SkipGrid -Update -BuildNetFX
```

**Comment by alayac** [comment]
@munkey01 before running Import-OSMedia, I run this to get the optional update(s)
Get-DownOSDBuilder -UpdateOS "Windows 10" -UpdateBuild 1909 -UpdateArch x64 -UpdateGroup Optional -Download
you may have to tweak for your needs.

**Comment by munkey01** [comment]
@alayac Thanks for the help. I’ll give this a try.
