### ISSUE TITLE
Allow ISO path and name to be set for New-OSDBuilderISO.ps1 or return ISO path

### ISSUE THREAD

**Issue by ryancbutler** [OSDeploy/OSDBuilder#4]
Looking at automating ISO builds for a vsphere environment and it would help a lot being able to either set the ISO path and name or return the name of the created ISO for further scripting.

**Comment by iainbrighton** [comment]
You could either update the `Public\New-OSDBuilderISO.ps1` file to include this:
```powershell
start-process $oscdimg -args @("-m","-o","-u2","-bootdata:$data",'-u2','-udfver102',$ISOLabel,"`"$ISOSourceFolder`"", "`"$ISOFile`"") -Wait
Write-Output -InputObject $ISOFile
```
I'm not sure what impact returning the ISO file path to the pipeline by default will/could cause? An alternative will be to add a `-PassThru` parameter to the function.

**Comment by ryancbutler** [comment]
I was thinking of returning it as an object since there could be multiple ISOs.  Something like
```
$object += @{
  ISO= $isopath
  Source = $ISOSourceFolder
  Label = $ISOLabel
}
return $object
```

I would be happy to create a PR just need to carve out some time and if we agree with the approach.

**Comment by OSDeploy** [comment]
Thanks!
