### ISSUE TITLE
Content path duplicated?

### ISSUE THREAD

**Issue by ARunholm** [OSDeploy/OSDBuilder#40]
Hi! I'm trying to do an OSBuild, using a newly created OSBuildTask. The problem I'm experiencing, is the the path to my Language packs under IsoExtract gets duplicated while running the OSBuild: C:\OSD\Content\C:\OSD\Content\IsoExtract...

Any hints on how to get around this? I've even tried shortening the path in the json file for the OSBuildTask, but that seems to make no impact at all.

**Comment by OSDeploy** [comment]
You have a trailing backslash in your OSDBuilder home.  Modify the Home
path and remove that trailing backslash

**Comment by ARunholm** [comment]
I've done that a couple of times and it doesn't show a trailing backslash.Home reads C:\OSD before and after an OsdBuilder -sethome C:\OSD Is there some other place where I can edit this?
/A
    Den onsdag 16 september 2020 16:00:51 CEST, David Segura <notifications@github.com> skrev:  
 
 

You have a trailing backslash in your OSDBuilder home. Modify the Home
path and remove that trailing backslash

**Comment by OSDeploy** [comment]
Manually edit the task then.  It should not have a full path, only a
relative one

**Comment by ARunholm** [comment]
After yet another update of OSDBuilder and a restart, all of a sudden the task json got properly built and now everything is running smoothly again. Thanks!
    Den onsdag 16 september 2020 16:22:06 CEST, David Segura <notifications@github.com> skrev:  
 
 

Manually edit the task then. It should not have a full path, only a
relative one

**Comment by OSDeploy** [comment]
Awesome!
