### ISSUE TITLE
Get-DownOSDBuilder does not support 2004/2009

### ISSUE THREAD

**Issue by Fabaderheld** [OSDeploy/OSDBuilder#42]
There is support for 20H2  but the cmdlet `Get-DownOSDBuilder` does not.
```
Cannot validate argument on parameter 'UpdateBuild'. The argument "2009" does not belong to the set
"1909,1903,1809,1803,1709,1703,1607,1511,1507,7601,7603" specified by the ValidateSet attribute. Supply an argument
that is in the set and then try the command again.
```
regards
Faba

**Comment by munkey01** [comment]
```
[Parameter(ParameterSetName='OSDUpdate')]
[ValidateSet (2009,2004,1909,1903,1809,1803,1709,1703,1607,1511,1507,7601,7603)]
[Alias('ReleaseId')]
[string]$UpdateBuild,
```

It looks like that commit occurred on[ 9/29](https://github.com/OSDeploy/OSDBuilder/commit/488c91a33246b3bc3f8b52d79a704701d52050a5#diff-6adef22244ffbe0aab90d671fb3c9d3e5a6c80dc404d02473e604759cebea7c3). 

Are you running the newest version of OSDBuilder? `Get-Module OSDBuilder` and check for the version 20.9.29.1. If it is a lower version, then try running `Update-Module OSDBuilder` and attempting again.

**Comment by Fabaderheld** [comment]
I'm pretty sure I did that before posting here, but I might just have updated ODSUS und not all modules, after forcing an update on all them it is working now.

sorry to bother you
