### ISSUE TITLE
Issue with PE drivers for storage?

### ISSUE THREAD

**Issue by ThiloLangbeinHUK** [OSDeploy/OSDBuilder#48]
I've created a new ISO with current OSDBuilder. Then I created a USB-key for installation, but computers SSD drives are not found during setup. winPE seems to be broken in some matter. Or is this a issue on my side?

**Comment by OSDeploy** [comment]
I believe this is an issue with the Controller not having drivers.  If you didn't add any drivers, then these things happen.  What's the Make of the computer?

**Comment by ThiloLangbeinHUK** [comment]
I thin there was a small bug (with WinPE drivers) which caused this issue. With the latest version everything runs fine.
