### ISSUE TITLE
WARNING: Unable to locate RegHive at D:\OSDBuilder\Mount\os084638\Windows\System32\Config\SOFTWARE (DISM 0x80070032)

### ISSUE THREAD

**Issue by HermanGB** [OSDeploy/OSDBuilder#63]
Windows Server 2019 (Version 1809 Build 17763.2183)
ADK (Version 10.1.22000.1)
ADK PE Add-ons (Version 10.1.22000.1)
ISO's tried:
SW_DVD9_Win_Pro_10_21H1_64BIT_English_Pro_Ent_EDU_N_MLF_X22-55036.ISO
SW_DVD9_Win_Pro_11_21H2_64BIT_English_Pro_Ent_EDU_N_MLF_-2_X22-82699.ISO
Module OSDBuilder (Version 21.10.12.1)
Module OSD (Version 21.10.12.1)

**Special circumstances:** 
Machine does not have access to internet. Modules are manually imported. 
D-Drive has dedup enabled. 

![image](https://user-images.githubusercontent.com/23094138/137444854-203c33c3-3b19-463a-a647-223c4d9daa0e.png)

**C:\Windows\Logs\DISM\Dism.log**

`
[28216] Mounting new image.

Wim:         [E:\Sources\install.wim]
Image Index: [3]
Mount Path:  [D:\OSDBuilder\Mount\os084638]
[28216] [0x80070032] EnableShortnamesOnApplyTarget:(548): The request is not supported.
[28216] [0x80070032] WIMSetFileShortName:(620): The request is not supported.
[28216] [0xd00000bb] WimImageSetInformationFile:(2367)
[28216] [0xc144012e] 
Error DISM   DISM WIM Provider: PID=28216 [RestoreHardlink:(556) -> setting hardlink failed] D:\OSDBuilder\Mount\os084638\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\Content.xml (HRESULT=0x80070032) - CWimManager::WimProviderMsgLogCallback
[28216] [0xd00000bb] RestoreHardlinks:(735)
[28216] [0xd00000bb] RestoreFileMetadata:(192)
[28216] [0xc144012e] 
Error DISM   DISM WIM Provider: PID=28216 [RestoreFileMetadata:(196) -> RestoreFileMetadata: RestoreHardlinks failed] D:\OSDBuilder\Mount\os084638\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\Content.xml (HRESULT=0x80070032) - CWimManager::WimProviderMsgLogCallback
[28216] [0xd00000bb] RestoreRefNode:(1722)
[28216] [0xc144012e] 
Error DISM   DISM WIM Provider: PID=28216 D:\OSDBuilder\Mount\os084638\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\Content.xml (HRESULT=0x80070032) - CWimManager::WimProviderMsgLogCallback
[28216] [0xd00000bb] RestoreRefNodeCallback:(1884)
[28216] [0xd00000bb] ProcessWimQueueNode:(98)
[28216] [0xd00000bb] DequeueWimData:(304)
[28216] [0xd00000bb] ImageWorkerThread:(250)
[28216] [0xd00000bb] GetImageErrorCode:(2837)
[28216] [0xd00000bb] RestoreFileNodeList:(2050)
[28216] [0xd00000bb] RestoreFilesCallback:(3963)
[28216] [0xd00000bb] EnumImageDataEntries:(1052)
[28216] [0xd00000bb] GetImageErrorCode:(2837)
[28216] [0xd00000bb] ImageWorkerThread:(198)
[28216] [0xd00000bb] RestoreAllData:(1101)
[28216] [0xd00000bb] WIMApplyImageInternal:(777)
[28216] [0x80070032] ImageStubMountDirectory:(985): The request is not supported.
[28216] [0x80070032] WIMMountImageHandle:(1275): The request is not supported.
[28216] [0x80004005] DeleteAndRestoreDirectory:(335): Unspecified error
[28216] [0xc1420117] DeleteAndRestoreDirectory:(336)
[28216] [0xc1420117] RestoreMountDirectory:(404)
[28216] [0xc1420117] WIMMountImageHandle:(1328)
Error DISM   DISM WIM Provider: PID=28216 TID=40892 "Failed to mount the image." - CWimImageInfo::Mount(hr:0x80070032)
Error DISM   API: PID=28216 TID=40892 onecore\base\ntsetup\opktools\dism\api\lib\imagingcommandobject.cpp:215 - CMountCommandObject::InternalExecute(hr:0x80070032)
Error DISM   API: PID=28216 TID=40892 InternalExecute failed - CBaseCommandObject::Execute(hr:0x80070032)
Error DISM   API: PID=28216 TID=36328 CMountCommandObject failed - MountImageInternal(hr:0x80070032)
Error DISM   API: PID=28216 TID=36328 onecore\base\ntsetup\opktools\dism\api\lib\dismgeneralapisinternal.cpp:632 - MountImageInternal(hr:0x80070032)
`

**A lot of files and directories are left under D:\OSDBuilder\Mount**

`
D:\OSDBuilder\Mount\os084638                                                                                                                                    
D:\OSDBuilder\Mount\os105423                                                                                                                                    
D:\OSDBuilder\Mount\os110004                                                                                                                                    
D:\OSDBuilder\Mount\os110641                                                                                                                                    
D:\OSDBuilder\Mount\os114251                                                                                                                                    
D:\OSDBuilder\Mount\os115155                                                                                                                                    
D:\OSDBuilder\Mount\os122912                                                                                                                                    
D:\OSDBuilder\Mount\os125141                                                                                                                                    
D:\OSDBuilder\Mount\os084638\Windows                                                                                                                            
D:\OSDBuilder\Mount\os084638\Windows\WinSxS                                                                                                                     
D:\OSDBuilder\Mount\os084638\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d                
D:\OSDBuilder\Mount\os084638\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\ipsar.xml      
D:\OSDBuilder\Mount\os084638\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\ipscat.xml     
D:\OSDBuilder\Mount\os084638\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\ipschs.xml     
D:\OSDBuilder\Mount\os084638\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\ipscsy.xml     
D:\OSDBuilder\Mount\os084638\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\ipsdan.xml     
D:\OSDBuilder\Mount\os105423\Windows                                                                                                                            
D:\OSDBuilder\Mount\os105423\Windows\WinSxS                                                                                                                     
D:\OSDBuilder\Mount\os105423\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d                
D:\OSDBuilder\Mount\os105423\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\ipsar.xml      
D:\OSDBuilder\Mount\os105423\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\ipscat.xml     
D:\OSDBuilder\Mount\os105423\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\ipschs.xml     
D:\OSDBuilder\Mount\os110004\Windows                                                                                                                            
D:\OSDBuilder\Mount\os110004\Windows\WinSxS                                                                                                                     
D:\OSDBuilder\Mount\os110004\Windows\WinSxS\amd64_microsoft-windows-t..-coreinkrecognition_31bf3856ad364e35_10.0.19041.746_none_cb918c7159c1f7d9                
D:\OSDBuilder\Mount\os110004\Windows\WinSxS\amd64_microsoft-windows-t..nkrecognition.en-ca_31bf3856ad364e35_10.0.19041.1_none_799aed230997c7b3                  
D:\OSDBuilder\Mount\os110004\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d                
D:\OSDBuilder\Mount\os110004\Windows\WinSxS\amd64_microsoft-windows-t..platform-comruntime_31bf3856ad364e35_10.0.19041.746_none_a889d2a595dea698                
D:\OSDBuilder\Mount\os110004\Windows\WinSxS\amd64_microsoft-windows-t..-coreinkrecognition_31bf3856ad364e35_10.0.19041.746_none_cb918c7159c1f7d9\hwrcommonlm.dat
D:\OSDBuilder\Mount\os110004\Windows\WinSxS\amd64_microsoft-windows-t..nkrecognition.en-ca_31bf3856ad364e35_10.0.19041.1_none_799aed230997c7b3\hwrenclm.dat     
D:\OSDBuilder\Mount\os110004\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\ipsar.xml      
D:\OSDBuilder\Mount\os110004\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\ipscat.xml     
D:\OSDBuilder\Mount\os110004\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\ipschs.xml     
D:\OSDBuilder\Mount\os110004\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\ipscht.xml     
D:\OSDBuilder\Mount\os110004\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\ipscsy.xml     
D:\OSDBuilder\Mount\os110004\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\ipsdan.xml     
D:\OSDBuilder\Mount\os110004\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\ipsdeu.xml     
D:\OSDBuilder\Mount\os110004\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\ipsel.xml      
D:\OSDBuilder\Mount\os110004\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\ipsen.xml      
D:\OSDBuilder\Mount\os110004\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\ipsesp.xml     
D:\OSDBuilder\Mount\os110004\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.19041.746_none_1da55dc225237a0d\ipsfin.xml     
D:\OSDBuilder\Mount\os110004\Windows\WinSxS\amd64_microsoft-windows-t..platform-comruntime_31bf3856ad364e35_10.0.19041.746_none_a889d2a595dea698\InkDiv.dll     
D:\OSDBuilder\Mount\os110641\Windows                                                                                                                            
D:\OSDBuilder\Mount\os110641\Windows\WinSxS                                                                                                                     
D:\OSDBuilder\Mount\os110641\Windows\WinSxS\amd64_microsoft-windows-t..-coreinkrecognition_31bf3856ad364e35_10.0.22000.1_none_43dbdf4affbbc684                  
D:\OSDBuilder\Mount\os110641\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.22000.1_none_95efb09bcb1d48b8                  
D:\OSDBuilder\Mount\os110641\Windows\WinSxS\amd64_microsoft-windows-t..-coreinkrecognition_31bf3856ad364e35_10.0.22000.1_none_43dbdf4affbbc684\hwrcommonlm.dat  
D:\OSDBuilder\Mount\os110641\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.22000.1_none_95efb09bcb1d48b8\ipsar.xml        
D:\OSDBuilder\Mount\os110641\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.22000.1_none_95efb09bcb1d48b8\ipscat.xml       
D:\OSDBuilder\Mount\os114251\Windows                                                                                                                            
D:\OSDBuilder\Mount\os114251\Windows\WinSxS                                                                                                                     
D:\OSDBuilder\Mount\os114251\Windows\WinSxS\amd64_microsoft-windows-t..-coreinkrecognition_31bf3856ad364e35_10.0.22000.1_none_43dbdf4affbbc684                  
D:\OSDBuilder\Mount\os114251\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.22000.1_none_95efb09bcb1d48b8                  
D:\OSDBuilder\Mount\os114251\Windows\WinSxS\amd64_microsoft-windows-t..-coreinkrecognition_31bf3856ad364e35_10.0.22000.1_none_43dbdf4affbbc684\hwrcommonlm.dat  
D:\OSDBuilder\Mount\os114251\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.22000.1_none_95efb09bcb1d48b8\ipsar.xml        
D:\OSDBuilder\Mount\os114251\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.22000.1_none_95efb09bcb1d48b8\ipscat.xml       
D:\OSDBuilder\Mount\os115155\Windows                                                                                                                            
D:\OSDBuilder\Mount\os115155\Windows\WinSxS                                                                                                                     
D:\OSDBuilder\Mount\os115155\Windows\WinSxS\amd64_microsoft-windows-t..-coreinkrecognition_31bf3856ad364e35_10.0.22000.1_none_43dbdf4affbbc684                  
D:\OSDBuilder\Mount\os115155\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.22000.1_none_95efb09bcb1d48b8                  
D:\OSDBuilder\Mount\os115155\Windows\WinSxS\amd64_microsoft-windows-t..-coreinkrecognition_31bf3856ad364e35_10.0.22000.1_none_43dbdf4affbbc684\hwrcommonlm.dat  
D:\OSDBuilder\Mount\os115155\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.22000.1_none_95efb09bcb1d48b8\ipsar.xml        
D:\OSDBuilder\Mount\os115155\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.22000.1_none_95efb09bcb1d48b8\ipscat.xml       
D:\OSDBuilder\Mount\os122912\Windows                                                                                                                            
D:\OSDBuilder\Mount\os122912\Windows\WinSxS                                                                                                                     
D:\OSDBuilder\Mount\os122912\Windows\WinSxS\amd64_microsoft-windows-t..-coreinkrecognition_31bf3856ad364e35_10.0.22000.1_none_43dbdf4affbbc684                  
D:\OSDBuilder\Mount\os122912\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.22000.1_none_95efb09bcb1d48b8                  
D:\OSDBuilder\Mount\os122912\Windows\WinSxS\amd64_microsoft-windows-t..-coreinkrecognition_31bf3856ad364e35_10.0.22000.1_none_43dbdf4affbbc684\hwrcommonlm.dat  
D:\OSDBuilder\Mount\os122912\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.22000.1_none_95efb09bcb1d48b8\ipsar.xml        
D:\OSDBuilder\Mount\os125141\Windows                                                                                                                            
D:\OSDBuilder\Mount\os125141\Windows\WinSxS                                                                                                                     
D:\OSDBuilder\Mount\os125141\Windows\WinSxS\amd64_microsoft-windows-t..-coreinkrecognition_31bf3856ad364e35_10.0.22000.1_none_43dbdf4affbbc684                  
D:\OSDBuilder\Mount\os125141\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.22000.1_none_95efb09bcb1d48b8                  
D:\OSDBuilder\Mount\os125141\Windows\WinSxS\amd64_microsoft-windows-t..-coreinkrecognition_31bf3856ad364e35_10.0.22000.1_none_43dbdf4affbbc684\hwrcommonlm.dat  
D:\OSDBuilder\Mount\os125141\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.22000.1_none_95efb09bcb1d48b8\ipsar.xml        
D:\OSDBuilder\Mount\os125141\Windows\WinSxS\amd64_microsoft-windows-t..nputpersonalization_31bf3856ad364e35_10.0.22000.1_none_95efb09bcb1d48b8\ipscat.xml       

`

When trying to clean up the files in the folder D:\OSDBuilder\Mount I get the following error message.
![image](https://user-images.githubusercontent.com/23094138/137446912-5c11eabb-2529-4cef-8843-f2b4647b6c7f.png)
I can successfully  delete the files if I change owner to administrator.

**Comment by OSDeploy** [comment]
Can you try with OSDBuilder on C, not D with Dedup and see if this changes things?  Also, what On Access Scanning do you have running for security?

**Comment by HermanGB** [comment]
Thanks for you quick reply! 
I updated to 21.10.14.1 and that did not solve the problem.
After changing the path to C:\ (no dedup) the script is able to complete successfully. 
So basically dism is unable to function properly on a drive with dedup enabled.
