### ISSUE TITLE
OSDBuilder not downloading June/2023 LCU update

### ISSUE THREAD

**Issue by Swelidingo** [OSDeploy/OSDBuilder#95]
I am having a problem updating my images as the osdbuilder just downloads May updates and not june.

**Comment by Simsi1986** [comment]
Works as designed, OSDSUS module needs an update, which depends on an update for the Windows Catalog CAB file.
Usually, OSDSUS module is updated within one week after patchday.

**Comment by Swelidingo** [comment]
it usually gets updated same day microsoft releases tuesday patches. i will be more patient and wait for 2 or 3 days. thanx for the response

**Comment by OSDeploy** [comment]
> it usually gets updated same day microsoft releases tuesday patches. i will be more patient and wait for 2 or 3 days. thanx for the response

This is correct.  June Patch Tuesday updates have not been added to the OSD Powershell Module.  Please give me a few more days to update this **free** project as my **real** job has been more time consuming this week.  Closing this thread as monthly updates to OSDBuilder are not guaranteed.

**Comment by Swelidingo** [comment]
it is kind of funny that i never thought there is someone updating the module in the background everymonth. your work is appreciated mate. if you need a volunteer to do this part every second Wednesday than i will be happy to do it. 
the updates showed up today.

**Comment by OSDeploy** [comment]
Thanks for that @Swelidingo  ... it's 4AM here and past my bedtime.
